/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  seo: {
    metaTitle: string;
    metaDescription: string;
    keywords?: string | null;
    canonicalUrl?: string | null;
    robots?: string | null;
    openGraph?: {
      ogTitle?: string | null;
      ogDescription?: string | null;
      ogType?: string | null;
      ogUrl?: string | null;
    };
  };
  hero: {
    eyebrow: string;
    titlePrefix: string;
    titleHighlight: string;
    titleSuffix?: string | null;
    description1: string;
    description2: string;
    formButtonLabel?: string | null;
    successTitle?: string | null;
    successDescription?: string | null;
    trustBadges?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  statsCards?: {
    items?:
      | {
          value: string;
          label: string;
          subLabel: string;
          iconName: string;
          id?: string | null;
        }[]
      | null;
  };
  servicesOverview: {
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    titleSuffix?: string | null;
    description: string;
    services?:
      | {
          title: string;
          description: string;
          iconName: string;
          link: string;
          linkLabel?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  medicalClaims: {
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    description: string;
    steps?:
      | {
          stepLabel: string;
          title: string;
          description: string;
          iconName: string;
          id?: string | null;
        }[]
      | null;
    metrics?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    primaryCta: {
      primaryLabel: string;
      primaryHref: string;
    };
    secondaryCta: {
      secondaryLabel: string;
      secondaryHref: string;
    };
  };
  trustStats: {
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    description: string;
    mainStats?:
      | {
          value: string;
          label: string;
          subLabel: string;
          iconName: string;
          id?: string | null;
        }[]
      | null;
    ratingBadges?:
      | {
          platform: string;
          label: string;
          value: string;
          subLabel?: string | null;
          color?: string | null;
          id?: string | null;
        }[]
      | null;
    bottomTitle?: string | null;
    bottomTitleHighlight?: string | null;
    bottomTitleSuffix?: string | null;
    bottomDescription?: string | null;
    checklist?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    happinessScore: {
      badge?: string | null;
      value: string;
      description?: string | null;
      linkLabel?: string | null;
      linkHref?: string | null;
    };
    billingExperts: {
      badge?: string | null;
      value: string;
      description?: string | null;
      linkLabel?: string | null;
      linkHref?: string | null;
    };
  };
  billingCta: {
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    description: string;
    ctaLabel: string;
    ctaHref: string;
    features?:
      | {
          title: string;
          description: string;
          iconName: string;
          id?: string | null;
        }[]
      | null;
  };
  doctorsTeam: {
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    description: string;
    floatingWidget1?: string | null;
    floatingWidget2?: string | null;
    traditionalAgencyText?: string | null;
    bellmedexText?: string | null;
    ctaLabel: string;
    ctaHref: string;
  };
  providerChallenges: {
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    description: string;
    challenges?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    formTitle?: string | null;
    formDescription?: string | null;
    formCtaLabel?: string | null;
  };
  specialtyBilling: {
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    description: string;
    specialties?:
      | {
          title: string;
          description: string;
          iconName: string;
          link: string;
          popular?: boolean | null;
          id?: string | null;
        }[]
      | null;
    ctaLabel: string;
    ctaHref: string;
  };
  nationwidePricing: {
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    description: string;
    benefits?:
      | {
          title: string;
          description: string;
          iconName: string;
          id?: string | null;
        }[]
      | null;
    primaryCta: {
      primaryLabel: string;
      primaryHref: string;
    };
    secondaryCta: {
      secondaryLabel: string;
      secondaryHref: string;
    };
    footerNote?: string | null;
  };
  pricingQuote: {
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    description: string;
    specialties?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    providerCounts?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    claimVolumes?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    services?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    highlights?:
      | {
          title: string;
          description: string;
          iconName: string;
          id?: string | null;
        }[]
      | null;
    trustBadges?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  testimonials: {
    preHeader?: string | null;
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    titleSuffix?: string | null;
    description: string;
    items?:
      | {
          name: string;
          specialty: string;
          clinicName?: string | null;
          text: string;
          avatarPath?: string | null;
          rating?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  faq: {
    badge: string;
    titlePlain: string;
    titleHighlight: string;
    description: string;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
    helpTitle?: string | null;
    helpDescription?: string | null;
    primaryCta: {
      primaryLabel: string;
      primaryHref: string;
    };
    secondaryCta: {
      secondaryLabel: string;
      secondaryHref: string;
    };
    footerNote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        canonicalUrl?: T;
        robots?: T;
        openGraph?:
          | T
          | {
              ogTitle?: T;
              ogDescription?: T;
              ogType?: T;
              ogUrl?: T;
            };
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        titlePrefix?: T;
        titleHighlight?: T;
        titleSuffix?: T;
        description1?: T;
        description2?: T;
        formButtonLabel?: T;
        successTitle?: T;
        successDescription?: T;
        trustBadges?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  statsCards?:
    | T
    | {
        items?:
          | T
          | {
              value?: T;
              label?: T;
              subLabel?: T;
              iconName?: T;
              id?: T;
            };
      };
  servicesOverview?:
    | T
    | {
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        titleSuffix?: T;
        description?: T;
        services?:
          | T
          | {
              title?: T;
              description?: T;
              iconName?: T;
              link?: T;
              linkLabel?: T;
              id?: T;
            };
      };
  medicalClaims?:
    | T
    | {
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        description?: T;
        steps?:
          | T
          | {
              stepLabel?: T;
              title?: T;
              description?: T;
              iconName?: T;
              id?: T;
            };
        metrics?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        primaryCta?:
          | T
          | {
              primaryLabel?: T;
              primaryHref?: T;
            };
        secondaryCta?:
          | T
          | {
              secondaryLabel?: T;
              secondaryHref?: T;
            };
      };
  trustStats?:
    | T
    | {
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        description?: T;
        mainStats?:
          | T
          | {
              value?: T;
              label?: T;
              subLabel?: T;
              iconName?: T;
              id?: T;
            };
        ratingBadges?:
          | T
          | {
              platform?: T;
              label?: T;
              value?: T;
              subLabel?: T;
              color?: T;
              id?: T;
            };
        bottomTitle?: T;
        bottomTitleHighlight?: T;
        bottomTitleSuffix?: T;
        bottomDescription?: T;
        checklist?:
          | T
          | {
              label?: T;
              id?: T;
            };
        happinessScore?:
          | T
          | {
              badge?: T;
              value?: T;
              description?: T;
              linkLabel?: T;
              linkHref?: T;
            };
        billingExperts?:
          | T
          | {
              badge?: T;
              value?: T;
              description?: T;
              linkLabel?: T;
              linkHref?: T;
            };
      };
  billingCta?:
    | T
    | {
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              iconName?: T;
              id?: T;
            };
      };
  doctorsTeam?:
    | T
    | {
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        description?: T;
        floatingWidget1?: T;
        floatingWidget2?: T;
        traditionalAgencyText?: T;
        bellmedexText?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  providerChallenges?:
    | T
    | {
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        description?: T;
        challenges?:
          | T
          | {
              label?: T;
              id?: T;
            };
        formTitle?: T;
        formDescription?: T;
        formCtaLabel?: T;
      };
  specialtyBilling?:
    | T
    | {
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        description?: T;
        specialties?:
          | T
          | {
              title?: T;
              description?: T;
              iconName?: T;
              link?: T;
              popular?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
      };
  nationwidePricing?:
    | T
    | {
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        description?: T;
        benefits?:
          | T
          | {
              title?: T;
              description?: T;
              iconName?: T;
              id?: T;
            };
        primaryCta?:
          | T
          | {
              primaryLabel?: T;
              primaryHref?: T;
            };
        secondaryCta?:
          | T
          | {
              secondaryLabel?: T;
              secondaryHref?: T;
            };
        footerNote?: T;
      };
  pricingQuote?:
    | T
    | {
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        description?: T;
        specialties?:
          | T
          | {
              label?: T;
              id?: T;
            };
        providerCounts?:
          | T
          | {
              label?: T;
              id?: T;
            };
        claimVolumes?:
          | T
          | {
              label?: T;
              id?: T;
            };
        services?:
          | T
          | {
              label?: T;
              id?: T;
            };
        highlights?:
          | T
          | {
              title?: T;
              description?: T;
              iconName?: T;
              id?: T;
            };
        trustBadges?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        preHeader?: T;
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        titleSuffix?: T;
        description?: T;
        items?:
          | T
          | {
              name?: T;
              specialty?: T;
              clinicName?: T;
              text?: T;
              avatarPath?: T;
              rating?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        badge?: T;
        titlePlain?: T;
        titleHighlight?: T;
        description?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        helpTitle?: T;
        helpDescription?: T;
        primaryCta?:
          | T
          | {
              primaryLabel?: T;
              primaryHref?: T;
            };
        secondaryCta?:
          | T
          | {
              secondaryLabel?: T;
              secondaryHref?: T;
            };
        footerNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}